name: dotnet package

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET ${{matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Display dotnet version
      run: dotnet --version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run Tests
      run: dotnet test --logger "trx;LogFileName=<TestResults.trx>"
#
#      - name: Create the package
#        run: dotnet pack --configuration Release <my project>
#      - name: Publish the package to GPR
#        run: dotnet nuget push <my project>/bin/Release/*.nupkg
#
#    - name: Publish the package to GPR
#      run: dotnet nuget push <my project>/bin/Release/*.nupkg
